# -*- coding: utf-8 -*-
"""Recipe scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15p4aO82tyHWoThtZzBfUcFcn2Z4ryKOn
"""

pip install mysql-connector-python

import numpy as np
import pandas as pd
from recipe_scrapers import scrape_me
  
import requests
from bs4 import BeautifulSoup

# url = 'https://www.allrecipes.com/recipe/36058/grilled-mushroom-swiss-burgers/?internalSource=streams&referringId=121&referringContentType=Recipe%20Hub&clickId=st_trending_s'
# scraper = scrape_me(url)

# scraper.title()
# scraper.total_time()
# scraper.yields()
# scraper.ingredients()
# scraper.instructions()
# scraper.image()
# scraper.links()

url = 'https://www.ah.nl/allerhande/recept/R-R1194010/tortilla-met-koolsalade-bonen-en-vissticks'

HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'}

page_data = requests.get(url, headers=HEADERS).content

soup = BeautifulSoup(page_data, "html.parser")

soup.title

ingredients = [item.text for item in soup.findAll("span", {"class":"js-label label"})]
ingredients

total_time = [item.text.replace('\n','').replace('min. bereiden','').replace(' min. oventijd','').split() for item in soup.findAll("li", {"class":"cooking-time"})][0]
total_time = np.sum(np.asarray(total_time).astype(float))
total_time